// Code generated by the Encore 1.48.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly catalog: catalog.ServiceClient
    public readonly channels: channels.ServiceClient
    public readonly dashboard: dashboard.ServiceClient
    public readonly finance: finance.ServiceClient
    public readonly ingredients: ingredients.ServiceClient
    public readonly products: products.ServiceClient
    public readonly promotions: promotions.ServiceClient
    public readonly recipes: recipes.ServiceClient
    public readonly reports: reports.ServiceClient
    public readonly sales: sales.ServiceClient
    public readonly settings: settings.ServiceClient
    public readonly shopping: shopping.ServiceClient
    public readonly targets: targets.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.catalog = new catalog.ServiceClient(base)
        this.channels = new channels.ServiceClient(base)
        this.dashboard = new dashboard.ServiceClient(base)
        this.finance = new finance.ServiceClient(base)
        this.ingredients = new ingredients.ServiceClient(base)
        this.products = new products.ServiceClient(base)
        this.promotions = new promotions.ServiceClient(base)
        this.recipes = new recipes.ServiceClient(base)
        this.reports = new reports.ServiceClient(base)
        this.sales = new sales.ServiceClient(base)
        this.settings = new settings.ServiceClient(base)
        this.shopping = new shopping.ServiceClient(base)
        this.targets = new targets.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getAdminDashboardStats as api_admin_dashboard_stats_getAdminDashboardStats } from "~backend/admin/dashboard_stats";
import {
    getLandingPageSettings as api_admin_landing_page_getLandingPageSettings,
    updateLandingPageSettings as api_admin_landing_page_updateLandingPageSettings
} from "~backend/admin/landing_page";
import {
    createTenant as api_admin_manage_users_createTenant,
    deleteTenant as api_admin_manage_users_deleteTenant,
    listTenants as api_admin_manage_users_listTenants,
    updateTenant as api_admin_manage_users_updateTenant
} from "~backend/admin/manage_users";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createTenant = this.createTenant.bind(this)
            this.deleteTenant = this.deleteTenant.bind(this)
            this.getAdminDashboardStats = this.getAdminDashboardStats.bind(this)
            this.getLandingPageSettings = this.getLandingPageSettings.bind(this)
            this.listTenants = this.listTenants.bind(this)
            this.updateLandingPageSettings = this.updateLandingPageSettings.bind(this)
            this.updateTenant = this.updateTenant.bind(this)
        }

        /**
         * Creates a new tenant.
         */
        public async createTenant(params: RequestType<typeof api_admin_manage_users_createTenant>): Promise<ResponseType<typeof api_admin_manage_users_createTenant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/tenants`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_manage_users_createTenant>
        }

        /**
         * Deletes a tenant.
         */
        public async deleteTenant(params: { id: string }): Promise<ResponseType<typeof api_admin_manage_users_deleteTenant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/tenants/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_manage_users_deleteTenant>
        }

        /**
         * Retrieves admin dashboard statistics.
         */
        public async getAdminDashboardStats(): Promise<ResponseType<typeof api_admin_dashboard_stats_getAdminDashboardStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/dashboard/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_dashboard_stats_getAdminDashboardStats>
        }

        /**
         * Retrieves landing page settings.
         */
        public async getLandingPageSettings(): Promise<ResponseType<typeof api_admin_landing_page_getLandingPageSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/landing-page/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_landing_page_getLandingPageSettings>
        }

        /**
         * Retrieves all tenants.
         */
        public async listTenants(): Promise<ResponseType<typeof api_admin_manage_users_listTenants>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/tenants`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_manage_users_listTenants>
        }

        /**
         * Updates landing page settings.
         */
        public async updateLandingPageSettings(params: RequestType<typeof api_admin_landing_page_updateLandingPageSettings>): Promise<ResponseType<typeof api_admin_landing_page_updateLandingPageSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/landing-page/settings`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_landing_page_updateLandingPageSettings>
        }

        /**
         * Updates a tenant.
         */
        public async updateTenant(params: RequestType<typeof api_admin_manage_users_updateTenant>): Promise<ResponseType<typeof api_admin_manage_users_updateTenant>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                email:  params.email,
                name:   params.name,
                phone:  params.phone,
                plan:   params.plan,
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/tenants/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_manage_users_updateTenant>
        }
    }
}


export namespace auth {
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createOrder as api_catalog_create_order_createOrder } from "~backend/catalog/create_order";
import { exportOrders as api_catalog_export_orders_exportOrders } from "~backend/catalog/export_orders";
import { generateReceipt as api_catalog_generate_receipt_generateReceipt } from "~backend/catalog/generate_receipt";
import { getSettings as api_catalog_get_settings_getSettings } from "~backend/catalog/get_settings";
import { listOrders as api_catalog_list_orders_listOrders } from "~backend/catalog/list_orders";
import { listProducts as api_catalog_list_products_listProducts } from "~backend/catalog/list_products";
import { updateOrderStatus as api_catalog_update_order_status_updateOrderStatus } from "~backend/catalog/update_order_status";
import {
    getDeliverySchedule as api_catalog_whatsapp_integration_getDeliverySchedule,
    processWhatsAppOrder as api_catalog_whatsapp_integration_processWhatsAppOrder
} from "~backend/catalog/whatsapp_integration";

export namespace catalog {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createOrder = this.createOrder.bind(this)
            this.exportOrders = this.exportOrders.bind(this)
            this.generateReceipt = this.generateReceipt.bind(this)
            this.getDeliverySchedule = this.getDeliverySchedule.bind(this)
            this.getSettings = this.getSettings.bind(this)
            this.listOrders = this.listOrders.bind(this)
            this.listProducts = this.listProducts.bind(this)
            this.processWhatsAppOrder = this.processWhatsAppOrder.bind(this)
            this.updateOrderStatus = this.updateOrderStatus.bind(this)
        }

        /**
         * Creates a new catalog order.
         */
        public async createOrder(params: RequestType<typeof api_catalog_create_order_createOrder>): Promise<ResponseType<typeof api_catalog_create_order_createOrder>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/orders`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_create_order_createOrder>
        }

        /**
         * Exports catalog orders to CSV format.
         */
        public async exportOrders(params: RequestType<typeof api_catalog_export_orders_exportOrders>): Promise<ResponseType<typeof api_catalog_export_orders_exportOrders>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/orders/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_export_orders_exportOrders>
        }

        /**
         * Generates receipt data for an order.
         */
        public async generateReceipt(params: { orderId: number }): Promise<ResponseType<typeof api_catalog_generate_receipt_generateReceipt>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/orders/${encodeURIComponent(params.orderId)}/receipt`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_generate_receipt_generateReceipt>
        }

        /**
         * Generates delivery schedule options.
         */
        public async getDeliverySchedule(): Promise<ResponseType<typeof api_catalog_whatsapp_integration_getDeliverySchedule>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/whatsapp/delivery-schedule`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_whatsapp_integration_getDeliverySchedule>
        }

        /**
         * Retrieves catalog settings and payment methods.
         */
        public async getSettings(): Promise<ResponseType<typeof api_catalog_get_settings_getSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_get_settings_getSettings>
        }

        /**
         * Retrieves all catalog orders.
         */
        public async listOrders(): Promise<ResponseType<typeof api_catalog_list_orders_listOrders>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/orders`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_list_orders_listOrders>
        }

        /**
         * Retrieves all active products for catalog.
         */
        public async listProducts(): Promise<ResponseType<typeof api_catalog_list_products_listProducts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/products`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_list_products_listProducts>
        }

        /**
         * Processes WhatsApp order and generates auto-reply.
         */
        public async processWhatsAppOrder(params: RequestType<typeof api_catalog_whatsapp_integration_processWhatsAppOrder>): Promise<ResponseType<typeof api_catalog_whatsapp_integration_processWhatsAppOrder>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/whatsapp/order`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_whatsapp_integration_processWhatsAppOrder>
        }

        /**
         * Updates order status and creates POS transaction when order is completed.
         */
        public async updateOrderStatus(params: RequestType<typeof api_catalog_update_order_status_updateOrderStatus>): Promise<ResponseType<typeof api_catalog_update_order_status_updateOrderStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/catalog/orders/status`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_catalog_update_order_status_updateOrderStatus>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createChannel as api_channels_create_channel_createChannel } from "~backend/channels/create_channel";
import { listChannels as api_channels_list_channels_listChannels } from "~backend/channels/list_channels";

export namespace channels {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createChannel = this.createChannel.bind(this)
            this.listChannels = this.listChannels.bind(this)
        }

        /**
         * Creates a new sales channel.
         */
        public async createChannel(params: RequestType<typeof api_channels_create_channel_createChannel>): Promise<ResponseType<typeof api_channels_create_channel_createChannel>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/channels`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_channels_create_channel_createChannel>
        }

        /**
         * Retrieves all sales channels.
         */
        public async listChannels(): Promise<ResponseType<typeof api_channels_list_channels_listChannels>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/channels`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_channels_list_channels_listChannels>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getStats as api_dashboard_stats_getStats } from "~backend/dashboard/stats";

export namespace dashboard {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getStats = this.getStats.bind(this)
        }

        /**
         * Retrieves dashboard statistics.
         */
        public async getStats(): Promise<ResponseType<typeof api_dashboard_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dashboard/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_stats_getStats>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getCashFlow as api_finance_cash_flow_getCashFlow } from "~backend/finance/cash_flow";
import { createExpense as api_finance_create_expense_createExpense } from "~backend/finance/create_expense";
import { listExpenseCategories as api_finance_list_expense_categories_listExpenseCategories } from "~backend/finance/list_expense_categories";
import { getProfitLoss as api_finance_profit_loss_getProfitLoss } from "~backend/finance/profit_loss";

export namespace finance {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createExpense = this.createExpense.bind(this)
            this.getCashFlow = this.getCashFlow.bind(this)
            this.getProfitLoss = this.getProfitLoss.bind(this)
            this.listExpenseCategories = this.listExpenseCategories.bind(this)
        }

        /**
         * Creates a new expense record.
         */
        public async createExpense(params: RequestType<typeof api_finance_create_expense_createExpense>): Promise<ResponseType<typeof api_finance_create_expense_createExpense>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/finance/expenses`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_finance_create_expense_createExpense>
        }

        /**
         * Generates cash flow report for specified period.
         */
        public async getCashFlow(params: RequestType<typeof api_finance_cash_flow_getCashFlow>): Promise<ResponseType<typeof api_finance_cash_flow_getCashFlow>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/finance/cash-flow`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_finance_cash_flow_getCashFlow>
        }

        /**
         * Generates profit and loss report for specified period.
         */
        public async getProfitLoss(params: RequestType<typeof api_finance_profit_loss_getProfitLoss>): Promise<ResponseType<typeof api_finance_profit_loss_getProfitLoss>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/finance/profit-loss`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_finance_profit_loss_getProfitLoss>
        }

        /**
         * Retrieves all expense categories.
         */
        public async listExpenseCategories(): Promise<ResponseType<typeof api_finance_list_expense_categories_listExpenseCategories>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/finance/expense-categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_finance_list_expense_categories_listExpenseCategories>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_ingredients_create_create } from "~backend/ingredients/create";
import { deleteIngredient as api_ingredients_delete_deleteIngredient } from "~backend/ingredients/delete";
import { exportIngredients as api_ingredients_export_exportIngredients } from "~backend/ingredients/export";
import { list as api_ingredients_list_list } from "~backend/ingredients/list";
import { update as api_ingredients_update_update } from "~backend/ingredients/update";

export namespace ingredients {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteIngredient = this.deleteIngredient.bind(this)
            this.exportIngredients = this.exportIngredients.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new ingredient.
         */
        public async create(params: RequestType<typeof api_ingredients_create_create>): Promise<ResponseType<typeof api_ingredients_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ingredients`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ingredients_create_create>
        }

        /**
         * Deletes an ingredient.
         */
        public async deleteIngredient(params: { id: number }): Promise<ResponseType<typeof api_ingredients_delete_deleteIngredient>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ingredients/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ingredients_delete_deleteIngredient>
        }

        /**
         * Exports ingredients to CSV format.
         */
        public async exportIngredients(): Promise<ResponseType<typeof api_ingredients_export_exportIngredients>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ingredients/export`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ingredients_export_exportIngredients>
        }

        /**
         * Retrieves all ingredients.
         */
        public async list(): Promise<ResponseType<typeof api_ingredients_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ingredients`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ingredients_list_list>
        }

        /**
         * Updates an existing ingredient.
         */
        public async update(params: RequestType<typeof api_ingredients_update_update>): Promise<ResponseType<typeof api_ingredients_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                costPerUnit:   params.costPerUnit,
                name:          params.name,
                stockQuantity: params.stockQuantity,
                supplier:      params.supplier,
                unit:          params.unit,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ingredients/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ingredients_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_products_create_create } from "~backend/products/create";
import { deleteProduct as api_products_delete_deleteProduct } from "~backend/products/delete";
import { exportProducts as api_products_export_exportProducts } from "~backend/products/export";
import { list as api_products_list_list } from "~backend/products/list";
import { update as api_products_update_update } from "~backend/products/update";

export namespace products {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteProduct = this.deleteProduct.bind(this)
            this.exportProducts = this.exportProducts.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new product.
         */
        public async create(params: RequestType<typeof api_products_create_create>): Promise<ResponseType<typeof api_products_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_products_create_create>
        }

        /**
         * Deletes a product.
         */
        public async deleteProduct(params: { id: number }): Promise<ResponseType<typeof api_products_delete_deleteProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_products_delete_deleteProduct>
        }

        /**
         * Exports products to CSV format.
         */
        public async exportProducts(): Promise<ResponseType<typeof api_products_export_exportProducts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/export`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_products_export_exportProducts>
        }

        /**
         * Retrieves all products.
         */
        public async list(): Promise<ResponseType<typeof api_products_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_products_list_list>
        }

        /**
         * Updates an existing product.
         */
        public async update(params: RequestType<typeof api_products_update_update>): Promise<ResponseType<typeof api_products_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                category:     params.category,
                costPrice:    params.costPrice,
                description:  params.description,
                isActive:     params.isActive,
                name:         params.name,
                recipeId:     params.recipeId,
                sellingPrice: params.sellingPrice,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_products_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createPromotion as api_promotions_create_promotion_createPromotion } from "~backend/promotions/create_promotion";
import { listPromotions as api_promotions_list_promotions_listPromotions } from "~backend/promotions/list_promotions";

export namespace promotions {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createPromotion = this.createPromotion.bind(this)
            this.listPromotions = this.listPromotions.bind(this)
        }

        /**
         * Creates a new promotion.
         */
        public async createPromotion(params: RequestType<typeof api_promotions_create_promotion_createPromotion>): Promise<ResponseType<typeof api_promotions_create_promotion_createPromotion>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/promotions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_promotions_create_promotion_createPromotion>
        }

        /**
         * Retrieves all promotions.
         */
        public async listPromotions(): Promise<ResponseType<typeof api_promotions_list_promotions_listPromotions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/promotions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_promotions_list_promotions_listPromotions>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_recipes_create_create } from "~backend/recipes/create";
import { deleteRecipe as api_recipes_delete_deleteRecipe } from "~backend/recipes/delete";
import { exportRecipes as api_recipes_export_exportRecipes } from "~backend/recipes/export";
import { list as api_recipes_list_list } from "~backend/recipes/list";
import { update as api_recipes_update_update } from "~backend/recipes/update";

export namespace recipes {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteRecipe = this.deleteRecipe.bind(this)
            this.exportRecipes = this.exportRecipes.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new recipe with ingredients.
         */
        public async create(params: RequestType<typeof api_recipes_create_create>): Promise<ResponseType<typeof api_recipes_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recipes_create_create>
        }

        /**
         * Deletes a recipe and its ingredients.
         */
        public async deleteRecipe(params: { id: number }): Promise<ResponseType<typeof api_recipes_delete_deleteRecipe>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recipes_delete_deleteRecipe>
        }

        /**
         * Exports recipes to CSV format.
         */
        public async exportRecipes(): Promise<ResponseType<typeof api_recipes_export_exportRecipes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes/export`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recipes_export_exportRecipes>
        }

        /**
         * Retrieves all recipes with their ingredients.
         */
        public async list(): Promise<ResponseType<typeof api_recipes_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recipes_list_list>
        }

        /**
         * Updates an existing recipe.
         */
        public async update(params: RequestType<typeof api_recipes_update_update>): Promise<ResponseType<typeof api_recipes_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                cookingTime:     params.cookingTime,
                description:     params.description,
                ingredients:     params.ingredients,
                name:            params.name,
                preparationTime: params.preparationTime,
                servingSize:     params.servingSize,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recipes/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recipes_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getInventoryReport as api_reports_inventory_report_getInventoryReport } from "~backend/reports/inventory_report";
import { getSalesReport as api_reports_sales_report_getSalesReport } from "~backend/reports/sales_report";

export namespace reports {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getInventoryReport = this.getInventoryReport.bind(this)
            this.getSalesReport = this.getSalesReport.bind(this)
        }

        /**
         * Generates inventory report.
         */
        public async getInventoryReport(): Promise<ResponseType<typeof api_reports_inventory_report_getInventoryReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reports/inventory`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reports_inventory_report_getInventoryReport>
        }

        /**
         * Generates sales report for specified date range.
         */
        public async getSalesReport(params: RequestType<typeof api_reports_sales_report_getSalesReport>): Promise<ResponseType<typeof api_reports_sales_report_getSalesReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reports/sales`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reports_sales_report_getSalesReport>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createTransaction as api_sales_create_transaction_createTransaction } from "~backend/sales/create_transaction";
import { exportTransactions as api_sales_export_transactions_exportTransactions } from "~backend/sales/export_transactions";
import { listTransactions as api_sales_list_transactions_listTransactions } from "~backend/sales/list_transactions";
import {
    getTransactionHistory as api_sales_transaction_history_getTransactionHistory,
    getTransactionReceipt as api_sales_transaction_history_getTransactionReceipt
} from "~backend/sales/transaction_history";

export namespace sales {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createTransaction = this.createTransaction.bind(this)
            this.exportTransactions = this.exportTransactions.bind(this)
            this.getTransactionHistory = this.getTransactionHistory.bind(this)
            this.getTransactionReceipt = this.getTransactionReceipt.bind(this)
            this.listTransactions = this.listTransactions.bind(this)
        }

        /**
         * Creates a new sales transaction.
         */
        public async createTransaction(params: RequestType<typeof api_sales_create_transaction_createTransaction>): Promise<ResponseType<typeof api_sales_create_transaction_createTransaction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/transactions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_create_transaction_createTransaction>
        }

        /**
         * Exports sales transactions to CSV format.
         */
        public async exportTransactions(params: RequestType<typeof api_sales_export_transactions_exportTransactions>): Promise<ResponseType<typeof api_sales_export_transactions_exportTransactions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/transactions/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_export_transactions_exportTransactions>
        }

        /**
         * Retrieves transaction history with filters.
         */
        public async getTransactionHistory(params: RequestType<typeof api_sales_transaction_history_getTransactionHistory>): Promise<ResponseType<typeof api_sales_transaction_history_getTransactionHistory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/transactions/history`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_transaction_history_getTransactionHistory>
        }

        /**
         * Retrieves transaction receipt for reprint.
         */
        public async getTransactionReceipt(params: { id: number }): Promise<ResponseType<typeof api_sales_transaction_history_getTransactionReceipt>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/transactions/${encodeURIComponent(params.id)}/receipt`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_transaction_history_getTransactionReceipt>
        }

        /**
         * Retrieves all sales transactions.
         */
        public async listTransactions(): Promise<ResponseType<typeof api_sales_list_transactions_listTransactions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/transactions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_list_transactions_listTransactions>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getSettings as api_settings_get_settings_getSettings } from "~backend/settings/get_settings";
import { updateSettings as api_settings_update_settings_updateSettings } from "~backend/settings/update_settings";

export namespace settings {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getSettings = this.getSettings.bind(this)
            this.updateSettings = this.updateSettings.bind(this)
        }

        /**
         * Retrieves store settings.
         */
        public async getSettings(): Promise<ResponseType<typeof api_settings_get_settings_getSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_settings_get_settings_getSettings>
        }

        /**
         * Updates store settings.
         */
        public async updateSettings(params: RequestType<typeof api_settings_update_settings_updateSettings>): Promise<ResponseType<typeof api_settings_update_settings_updateSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/settings`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_settings_update_settings_updateSettings>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { calculateNeeds as api_shopping_calculate_needs_calculateNeeds } from "~backend/shopping/calculate_needs";
import { createShoppingList as api_shopping_create_shopping_list_createShoppingList } from "~backend/shopping/create_shopping_list";
import { exportNeeds as api_shopping_export_needs_exportNeeds } from "~backend/shopping/export_needs";
import { listNeeds as api_shopping_list_needs_listNeeds } from "~backend/shopping/list_needs";

export namespace shopping {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.calculateNeeds = this.calculateNeeds.bind(this)
            this.createShoppingList = this.createShoppingList.bind(this)
            this.exportNeeds = this.exportNeeds.bind(this)
            this.listNeeds = this.listNeeds.bind(this)
        }

        /**
         * Calculates shopping needs based on current stock and recipe requirements.
         */
        public async calculateNeeds(params: RequestType<typeof api_shopping_calculate_needs_calculateNeeds>): Promise<ResponseType<typeof api_shopping_calculate_needs_calculateNeeds>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/calculate-needs`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_calculate_needs_calculateNeeds>
        }

        /**
         * Creates a shopping list from selected needs.
         */
        public async createShoppingList(params: RequestType<typeof api_shopping_create_shopping_list_createShoppingList>): Promise<ResponseType<typeof api_shopping_create_shopping_list_createShoppingList>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/lists`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_create_shopping_list_createShoppingList>
        }

        /**
         * Exports shopping needs to CSV format.
         */
        public async exportNeeds(): Promise<ResponseType<typeof api_shopping_export_needs_exportNeeds>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/needs/export`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_export_needs_exportNeeds>
        }

        /**
         * Retrieves all shopping needs.
         */
        public async listNeeds(): Promise<ResponseType<typeof api_shopping_list_needs_listNeeds>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/needs`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_list_needs_listNeeds>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createTarget as api_targets_create_target_createTarget } from "~backend/targets/create_target";
import { listTargets as api_targets_list_targets_listTargets } from "~backend/targets/list_targets";

export namespace targets {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createTarget = this.createTarget.bind(this)
            this.listTargets = this.listTargets.bind(this)
        }

        /**
         * Creates a new sales target.
         */
        public async createTarget(params: RequestType<typeof api_targets_create_target_createTarget>): Promise<ResponseType<typeof api_targets_create_target_createTarget>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/targets`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_targets_create_target_createTarget>
        }

        /**
         * Retrieves all sales targets.
         */
        public async listTargets(): Promise<ResponseType<typeof api_targets_list_targets_listTargets>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/targets`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_targets_list_targets_listTargets>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
